honeypot_fields
CleanTalk/wordpress-antispam pull request #121
Opened 2022-05-05 18:38 UTC by alexandergull

2022-05-06 04:47 UTC, Glomberg requested changes

2022-05-06 04:47 UTC, Glomberg commented on inc/cleantalk-public-integrations.php
> +            $base_call_data['sender_info']['honeypot_field_source'] = 'url';
We have a Post class to getting any _POST variables. Use it instead of direct _POST access.

2022-05-10 16:11 UTC, Glomberg approved these changes

2022-05-11 05:55 UTC, safronik approved these changes

2022-05-11 06:04 UTC, merged