Refactoring aa
CleanTalk/wordpress-antispam pull request #126
Opened 2022-05-24 10:56 UTC by ArtemAnoshin

2022-05-24 13:53 UTC, safronik requested changes

2022-05-26 04:21 UTC, alexandergull commented on inc/cleantalk-public-integrations.php
> +				return $errors;
What about skipping log filling? Needs to debug missed requests.

 do_action('apbct_skipped_request', __FILE__ . ' -> ' . __FUNCTION__ . '():' . __LINE__, $_POST);

2022-05-26 04:23 UTC, alexandergull requested changes
1) Agreed with Roman's comments
2) Skipped request logging required in Formidable changes

2022-05-26 09:24 UTC, Glomberg commented
Need to do more refactoring on the Helper class.

2022-05-26 09:24 UTC, closed without merging