Validate URL exclusions.
CleanTalk/wordpress-antispam pull request #130
Opened 2022-05-27 09:20 UTC by Glomberg

2022-05-30 06:10 UTC, ArtemAnoshin approved these changes

2022-05-31 06:57 UTC, safronik requested changes

2022-05-31 06:57 UTC, safronik commented on lib/Cleantalk/Common/Validate.php
> +        return @preg_match('/' . $regexp . '/', '') !== false;
Better to @ delimiter here, to avoid conflicts for cases when delimiters are passed  to the function.

2022-05-31 06:57 UTC, safronik commented on lib/Cleantalk/Common/Validate.php
> +        return @preg_match('/' . $regexp . '/', '') !== false;
Please, compare with integer 1 here https://www.php.net/manual/en/function.preg-match.php#refsect1-function.preg-match-returnvalues

2022-05-31 07:10 UTC, safronik commented on lib/Cleantalk/Common/Validate.php
> +        return @preg_match('/' . $regexp . '/', '') !== false;
Everything is ok!

2022-05-31 07:10 UTC, safronik approved these changes

2022-05-31 07:42 UTC, merged