Added Sanitize::stripTags method
CleanTalk/wordpress-antispam pull request #144
Opened 2022-06-21 09:15 UTC by ArtemAnoshin

2022-06-22 06:10 UTC, Glomberg approved these changes

2022-06-22 07:15 UTC, safronik requested changes
Please, delete redundant strip_tags call.

2022-06-29 05:32 UTC, alexandergull approved these changes

2022-06-29 08:25 UTC, Glomberg commented
Reject. These edits are redundand.

2022-06-29 08:25 UTC, closed without merging