Processed by Psalm: cleantalk-oublic-validate.php; Made a condition f…
CleanTalk/wordpress-antispam pull request #153
Opened 2022-07-18 10:48 UTC by ArtemAnoshin

…or resetting the check to separate functions

2022-07-18 12:54 UTC, alexandergull requested changes

2022-07-18 12:54 UTC, alexandergull commented on inc/cleantalk-public-validate-skip-functions.php
> +function skip_for_ct_contact_form_validate()
Can we use more friendly names? Function name should reflect what it does. FE: if ( ct_contact_form_validate_skipped() ){}

2022-07-18 12:54 UTC, alexandergull commented on inc/cleantalk-public-validate-skip-functions.php
> +function skip_for_ct_contact_form_validate_postdata()
Can we use more friendly names? Function name should reflect what it does. FE: if ( ct_contact_form_validate_postdata_skipped() ){}

2022-07-18 12:55 UTC, alexandergull requested changes
See the cooments, please.

2022-07-26 06:07 UTC, Glomberg approved these changes

2022-07-26 16:43 UTC, merged