wpForo - add topic and post under protection
CleanTalk/wordpress-antispam pull request #182
Opened 2022-10-20 10:09 UTC by ArtemAnoshin

2022-10-24 11:59 UTC, alexandergull requested changes
Do we really need to use two integration classes? I see they do the same actions. I presume we could use the same class for both hooks.

2022-10-25 05:55 UTC, Glomberg commented
> Do we really need to use two integration classes? I see they do the same actions. I presume we could use the same class for both hooks.

I'm agree too. Replace two integrations into an one. Into 'hook' parameter you can pass an array of the hooks.

2022-10-27 06:26 UTC, Glomberg approved these changes

2022-10-28 07:56 UTC, alexandergull approved these changes

2022-10-28 10:51 UTC, merged