Not create cookies until key sync
CleanTalk/wordpress-antispam pull request #195
Opened 2022-11-15 09:27 UTC by svfcode

2022-11-15 09:46 UTC, Glomberg requested changes

2022-11-15 09:46 UTC, Glomberg commented on js/src/apbct-public--2--public.js
> +	if (ctPublic.data__key_is_ok) {
It would be better not to init these intervals completely if the key is not checked yet.

2022-11-15 10:28 UTC, Glomberg approved these changes

2022-11-16 04:42 UTC, ArtemAnoshin approved these changes

2022-11-16 04:44 UTC, merged