Private lists management via remote calls
CleanTalk/wordpress-antispam pull request #202
Opened 2022-11-24 09:14 UTC by alexandergull

2022-11-29 06:02 UTC, Glomberg requested changes

2022-11-29 06:02 UTC, Glomberg commented on cleantalk.php
> +            try {
Not need to catch exceptions here.

2022-11-29 08:47 UTC, alexandergull commented on cleantalk.php
> +            try {
Right, fixed.

2022-11-30 04:19 UTC, ArtemAnoshin approved these changes

2022-11-30 04:26 UTC, merged