New multisite logic implemented.
CleanTalk/wordpress-antispam pull request #25
Opened 2021-09-03 11:58 UTC by Glomberg

2021-09-03 23:35 UTC, shagimuratov approved these changes
Everything is good.

2021-09-06 11:32 UTC, safronik requested changes

2021-09-06 11:32 UTC, safronik commented on lib/Cleantalk/ApbctWP/State.php
> +			$this->notice_show  = $this->notice_show || count( (array) $this->errors );
Maybe (bool) $this->errors could be more easier to understand?

2021-09-06 11:41 UTC, Glomberg commented on inc/cleantalk-ajax-handlers.php
> +$apbct->allow_custom_key = $apbct->network_settings['multisite__work_mode'] = 3;
https://github.com/CleanTalk/wordpress-antispam/pull/25/commits/b84fc727692b2a8171b440965c7a8a3b5e2d58ab

2021-09-06 11:50 UTC, merged