New. SFW. Fall back updating system implemented.
CleanTalk/wordpress-antispam pull request #29
Opened 2021-09-13 15:52 UTC by Glomberg

2021-09-14 06:50 UTC, ArtemAnoshin commented on lib/Cleantalk/ApbctWP/Firewall/SFW.php
> +        if ( empty($result['error']) ) {
Почему бы не делать так:
если ошибка - вернули ошибку.
Дальше код.
Сейчас если нет ошибки - то делаем код. Визуально код, который валидный, выглядит так как будто он у нас выполнится в результате исключения какого. А он выполнится всегда почти. 
Т.е. примерно так я вижу:
if(isset($result['error'])) return false;

Тут все остальное.

2021-09-14 06:50 UTC, ArtemAnoshin commented on lib/Cleantalk/ApbctWP/Firewall/SFW.php
> +        for ( $count_result = 0; current($blacklists) !== false; ) {
Циклы for сложно понимать, почему бы просто форычем по массиву не бежать?
Я бы for использовал только если у нас реально индекс i в теле что то решает.

2021-09-14 08:38 UTC, Glomberg commented on lib/Cleantalk/ApbctWP/Firewall/SFW.php
> +        for ( $count_result = 0; current($blacklists) !== false; ) {
$count_result is using in the nested loop

2021-09-15 05:00 UTC, safronik requested changes

2021-09-15 10:13 UTC, Glomberg commented on lib/Cleantalk/ApbctWP/Firewall/AntiCrawler.php
> +                        $entry[1]
Solved https://github.com/CleanTalk/wordpress-antispam/commit/61a805b471d01190472d080b18079ae4d412a56b

2021-09-15 10:13 UTC, Glomberg commented on cleantalk.php
> +        apbct_activation__create_tables(Schema::getSchema('sfw'), $apbct->db_prefix);
Solved https://github.com/CleanTalk/wordpress-antispam/commit/18e608418b21353bf468947e8eb34526e5ec1918

2021-09-15 10:14 UTC, Glomberg commented on lib/Cleantalk/ApbctWP/Firewall/AntiCrawler.php
> +                    \Cleantalk\ApbctWP\DB::getInstance()->execute($query);
Solved https://github.com/CleanTalk/wordpress-antispam/commit/3c59d63da4f92d986110eadfa1dfc182db43cff6

2021-09-15 10:14 UTC, Glomberg commented on lib/Cleantalk/ApbctWP/Firewall/SFW.php
> +                $db->execute($query);
Solved https://github.com/CleanTalk/wordpress-antispam/commit/3c59d63da4f92d986110eadfa1dfc182db43cff6

2021-09-15 11:30 UTC, merged