New. WPCLI. Possibility to create service, set template and toggle settings.
CleanTalk/wordpress-antispam pull request #327
Opened 2023-12-29 07:35 UTC by svfcode

2024-01-10 11:41 UTC, alexandergull approved these changes

2024-01-11 07:10 UTC, Glomberg requested changes
Please, fix psalm notices https://github.com/CleanTalk/wordpress-antispam/actions/runs/7485396384/job/20373787239

2024-01-12 09:07 UTC, svfcode commented
> Please, fix psalm notices https://github.com/CleanTalk/wordpress-antispam/actions/runs/7485396384/job/20373787239

Thanks, fixed https://github.com/CleanTalk/wordpress-antispam/pull/327/commits/e79e9355d6583d54562cb8c9667c5b4c808fb0a2

2024-01-16 06:25 UTC, Glomberg approved these changes

2024-01-16 07:39 UTC, merged