Upd. ApbctSFW. Switch to direct update
CleanTalk/wordpress-antispam pull request #350
Opened 2024-03-13 18:40 UTC by AntonV1211

https://doboard.com/1/task/6350

2024-03-15 06:26 UTC, Glomberg requested changes

2024-03-15 06:26 UTC, Glomberg commented on cleantalk.php
> +    $apbct->fw_stats['reason_direct_update_log'] = null;
Please, add this array key `reason_direct_update_log` in the default `fw_stats` array contained in the `State` class

2024-03-18 05:57 UTC, Glomberg commented on cleantalk.php
> +    $apbct->fw_stats['reason_direct_update_log'] = null;
https://github.com/CleanTalk/wordpress-antispam/pull/350/commits/707cafe7f4da371bf0126633bae0dcc8a0b938ea

2024-03-18 05:57 UTC, Glomberg approved these changes

2024-03-18 09:39 UTC, alexandergull approved these changes

2024-03-18 09:42 UTC, merged