Fix. Overwriting email if found longer
CleanTalk/wordpress-antispam pull request #373
Opened 2024-06-10 08:07 UTC by AntonV1211

https://doboard.com/1/task/8217

2024-06-11 05:36 UTC, Glomberg requested changes

2024-06-11 05:36 UTC, Glomberg commented on inc/cleantalk-public-integrations.php
>      $data = ct_gfa($input_array);
Pass `$long_email` into `ct_gfa()` by second parameter. And you will not need to calculate `$sender_email` below.

2024-06-11 08:31 UTC, alexandergull approved these changes

2024-06-13 10:06 UTC, Glomberg approved these changes

2024-06-17 07:57 UTC, svfcode approved these changes

2024-06-25 12:54 UTC, merged