Fix. Fixing CF7 integration
CleanTalk/wordpress-antispam pull request #375
Opened 2024-06-10 14:38 UTC by AntonV1211

https://doboard.com/1/task/8304

2024-06-10 18:55 UTC, Glomberg requested changes

2024-06-10 18:55 UTC, Glomberg commented on inc/cleantalk-public-integrations.php
> +                $response["message"] = "***Forbidden. Sender blacklisted. Blocked by CleanTalk***";
The block message must be gathered from the cloud response. Use `$ct_result->comment` instead of hard-coded block message.

2024-06-11 05:29 UTC, Glomberg approved these changes

2024-06-11 05:40 UTC, alexandergull requested changes

2024-06-11 05:40 UTC, alexandergull commented on inc/cleantalk-public-integrations.php
> +            apbct_form__contactForm7__testSpam(false);
This code will be executed independent of the `if` condition. Please move this out from to simplify.

2024-06-13 10:06 UTC, Glomberg approved these changes

2024-06-17 07:56 UTC, svfcode approved these changes

2024-06-18 12:07 UTC, alexandergull approved these changes

2024-06-25 12:54 UTC, merged