Fix pixel av
CleanTalk/wordpress-antispam pull request #384
Opened 2024-06-16 19:05 UTC by AntonV1211

https://doboard.com/1/task/8280

2024-06-17 07:29 UTC, svfcode approved these changes

2024-06-18 05:43 UTC, Glomberg requested changes

2024-06-18 05:43 UTC, Glomberg commented on js/src/apbct-public--2--public.js
> +    console.log(resultDataJson.apbct_pixel_url);
Forgotten debug statement

2024-06-26 06:29 UTC, Glomberg approved these changes

2024-07-09 12:56 UTC, merged