Fix. Integration fix Kali Form
CleanTalk/wordpress-antispam pull request #403
Opened 2024-07-10 18:07 UTC by AntonV1211

https://doboard.com/1/task/8521

2024-07-11 04:55 UTC, svfcode approved these changes

2024-07-11 06:42 UTC, Glomberg approved these changes

2024-07-11 06:42 UTC, Glomberg requested changes
https://github.com/CleanTalk/wordpress-antispam/pull/403/files#r1673488575

2024-07-11 09:09 UTC, alexandergull approved these changes

2024-07-12 05:57 UTC, Glomberg approved these changes

2024-07-23 12:24 UTC, merged