Upd. Сhanging the Form signs exceptions link
CleanTalk/wordpress-antispam pull request #414
Opened 2024-07-16 15:19 UTC by AntonV1211

https://doboard.com/1/task/7161

2024-07-16 16:50 UTC, alexandergull requested changes

2024-07-16 16:50 UTC, alexandergull commented on lib/Cleantalk/ApbctWP/LinkConstructor.php
> +            'utm_campaign' => 'ABPCT_Settings',
Campaign is already set by defaults as @var in local LinkConstructor class.

2024-07-16 16:50 UTC, alexandergull commented on lib/Cleantalk/ApbctWP/LinkConstructor.php
> +            'utm_source' => 'apbct_hint_exclusions__form_signs',
The utm_source should show what the common source that had called the link click. 

The utm_medium is used to specify this place in more details

Something like this:
..
            'utm_id' => '',
            'utm_term' => '',
            'utm_source' => 'admin_panel',  //WP place
            'utm_medium' => 'settings', // WP place details
            'utm_content' => 'apbct_hint_exclusions__form_signs', //the link destination
...

2024-07-17 05:34 UTC, Glomberg approved these changes

2024-07-17 06:25 UTC, svfcode approved these changes

2024-07-18 18:35 UTC, alexandergull approved these changes

2024-07-18 18:36 UTC, merged