Integartion otter blocks
CleanTalk/wordpress-antispam pull request #425
Opened 2024-08-06 08:09 UTC by AntonV1211

https://doboard.com/task/9196

2024-08-07 05:56 UTC, Glomberg approved these changes

2024-08-08 18:22 UTC, alexandergull requested changes

2024-08-08 18:22 UTC, alexandergull commented on lib/Cleantalk/Antispam/Integrations/OtterBlocksForm.php
> +        $this->form_data_request = $argument;
Validate that the $argument is instance of the class expected and if the class has such methods (set_error & get_fields).

If this validation ignored there will be fatal errors if the plugin suddenly updated with the class changes.

2024-08-09 18:45 UTC, alexandergull approved these changes

2024-08-11 02:31 UTC, merged