Litespeed adjust av
CleanTalk/wordpress-antispam pull request #429
Opened 2024-08-11 04:30 UTC by AntonV1211

https://doboard.com/1/task/9310

2024-08-14 06:43 UTC, Glomberg requested changes

2024-08-14 06:43 UTC, Glomberg commented on lib/Cleantalk/ApbctWP/AdjustToEnvironmentModule/AdjustToEnv/AdjustToEnvLiteSpeedCache.php
> +        $comment = 'Disabled - TTL 1 day';
Get the phrase translatable.

2024-08-14 06:43 UTC, Glomberg commented on lib/Cleantalk/ApbctWP/AdjustToEnvironmentModule/AdjustToEnv/AdjustToEnvLiteSpeedCache.php
> +            $comment = 'Enable - back TTL 1 week';
Get the phrase translatable.

2024-08-14 06:43 UTC, Glomberg commented on lib/Cleantalk/ApbctWP/AdjustToEnvironmentModule/AdjustToEnv/AdjustToEnvLiteSpeedCache.php
> +                $current_config_ttl_pub = (bool)get_network_option(0, 'litespeed.conf.cache-ttl_pub');
Use `get_option` instead of `get_network_option`

2024-08-14 06:43 UTC, Glomberg commented on lib/Cleantalk/ApbctWP/AdjustToEnvironmentModule/AdjustToEnv/AdjustToEnvLiteSpeedCache.php
> +        $current_config_ttl_pub = (int)get_network_option(0, 'litespeed.conf.cache-ttl_pub');
Use `get_option` instead of `get_network_option`

2024-08-19 08:05 UTC, Glomberg approved these changes

2024-08-20 12:38 UTC, AntonV1211 commented on lib/Cleantalk/ApbctWP/AdjustToEnvironmentModule/AdjustToEnv/AdjustToEnvLiteSpeedCache.php
> +use LiteSpeed\Purge;
About the "namespace" and "use class", there were no errors during the test, we specifically checked the operation of the plugin without the necessary class and namespace

2024-08-20 12:58 UTC, svfcode approved these changes

2024-08-20 13:01 UTC, merged