New. Form decoration. `Holiday form decoration` option added.
CleanTalk/wordpress-antispam pull request #432
Opened 2024-08-20 10:02 UTC by Glomberg

https://doboard.com/task/8294

2024-08-20 12:07 UTC, svfcode approved these changes

2024-12-13 11:42 UTC, svfcode requested changes

2024-12-13 11:42 UTC, svfcode commented on lib/Cleantalk/ApbctWP/FormDecorator/DecorationSet.php
> +        //    display: flex;
Remove comments please.

2024-12-16 05:24 UTC, AntonV1211 commented on lib/Cleantalk/ApbctWP/FormDecorator/DecorationSet.php
> +        //    display: flex;
Ok

2024-12-16 07:38 UTC, alexandergull commented on lib/Cleantalk/ApbctWP/GetFieldsAny.php
> +                        $this->processed_data['message'][$nested_array_key] = $value_for_email;
Please, revive this from dev branch

2024-12-16 07:38 UTC, alexandergull commented on lib/Cleantalk/ApbctWP/GetFieldsAny.php
> +                        $this->processed_data['emails_array'][$nested_array_key] = $value_for_email;
Please, revive this from dev branch

2024-12-16 07:38 UTC, alexandergull commented on lib/Cleantalk/ApbctWP/GetFieldsAny.php
> +                        $this->processed_data['message'][$nested_array_key] = $value;
Please, revive this from dev branch

2024-12-16 07:38 UTC, alexandergull commented on lib/Cleantalk/ApbctWP/GetFieldsAny.php
> +                    $this->processed_data['message'][$nested_array_key] = $value;
Please, revive this from dev branch

2024-12-16 07:38 UTC, alexandergull commented on lib/Cleantalk/ApbctWP/GetFieldsAny.php
> +                $this->prev_name    = ($this->prev_name === '' ? $key : $this->prev_name . $key);
Please, revive this from dev branch

2024-12-16 07:40 UTC, alexandergull commented on lib/Cleantalk/ApbctWP/GetFieldsAny.php
> +
Please, revive this from dev branch

2024-12-16 07:40 UTC, alexandergull commented on lib/Cleantalk/ApbctWP/GetFieldsAny.php
> +        return $fields;
Please, revive this from dev branch

2024-12-16 12:20 UTC, svfcode approved these changes

2024-12-17 05:12 UTC, alexandergull approved these changes

2024-12-19 12:14 UTC, svfcode commented
Pull was merged through branch release_6.47.

2024-12-19 12:14 UTC, closed without merging