EmailEnocer SSL updates
CleanTalk/wordpress-antispam pull request #471
Opened 2024-10-25 08:07 UTC by alexandergull

https://doboard.com/1/task/11932

2024-10-25 09:34 UTC, svfcode approved these changes

2024-10-28 07:22 UTC, Glomberg requested changes

2024-10-28 07:22 UTC, Glomberg commented on lib/Cleantalk/Antispam/EmailEncoder.php
> +                throw new \Exception('Can\'t encode plain string');
Please, add more error info into the exception. Use the [`error_get_last()`](https://www.php.net/manual/en/function.error-get-last.php) function to get more details.

2024-10-28 07:22 UTC, Glomberg commented on lib/Cleantalk/Antispam/EmailEncoder.php
> +                throw new \Exception('Can\'t finish SSL decryption');
Please, add more error info into the exception too.

2024-10-28 07:22 UTC, Glomberg commented on tests/Antispam/EmailEncoderTest.php
> +class EmailEncoderTest extends TestCase
👍 💪

2024-10-28 10:03 UTC, merged