Psalm Level 3 Interation.
CleanTalk/wordpress-antispam pull request #481
Opened 2024-11-02 12:52 UTC by alexandergull

https://doboard.com/1/task/12367

2024-11-05 07:17 UTC, Glomberg requested changes

2024-11-05 07:17 UTC, Glomberg commented on lib/Cleantalk/ApbctWP/FindSpam/UsersChecker.php
> +            $ip_of_user_meta = TT::getArrayValueAsString($user_meta, 'ip');
A bug is here: `TT::getArrayValueAsString` here will find `$user_meta['ip']` but not `$user_meta[0]['ip']` needed.

2024-11-05 07:17 UTC, Glomberg commented on lib/Cleantalk/ApbctWP/FindSpam/UsersChecker.php
> +            $ip_of_user_meta = TT::getArrayValueAsString($user_meta, 'ip');
A bug is here: `TT::getArrayValueAsString` here will find `$user_meta['ip']` but not `$user_meta[0]['ip']` needed.

2024-11-11 10:44 UTC, alexandergull commented on lib/Cleantalk/Antispam/Cleantalk.php
> +            ? $url . '/' . $this->method_uri
api2.0 is a part of URL and should not be a GET param, got this verified

2024-11-11 11:01 UTC, alexandergull commented on lib/Cleantalk/Antispam/Cleantalk.php
> +        $url = !empty($this->method_uri) && is_string($this->method_uri)
I can not do it right now without refactoring. The api2.0/api3.0 difference is not implemented in the common lib. This chunk use method_uri param and all the logic that use setPresets() logic. We can't just modify the whole common lib not being sure that all the CMS call implemented setPresets() method and the provided preset exists - look for https://github.com/CleanTalk/_antispam/blob/14b70bfd579e7476e31f0de19d9f187dd73984e7/Cleantalk.php#L466

2024-11-11 11:37 UTC, merged