Fix. SFW Error Text. Checking whether the init or plugins_loaded hook was executed
CleanTalk/wordpress-antispam pull request #505
Opened 2024-11-29 15:00 UTC by AntonV1211

https://doboard.com/1/task/14722

2024-12-02 07:14 UTC, svfcode approved these changes

2024-12-03 07:39 UTC, alexandergull requested changes
I believe that errorToggle on init hook is a better solution.

2024-12-04 06:49 UTC, Glomberg requested changes

2024-12-04 06:49 UTC, Glomberg commented on cleantalk.php
> +    if (did_action( 'plugins_loaded' ) || did_action( 'init' )) {
Something same instead of the provided condition:
```php
add_action('init', function() {
    $apbct->errorToggle();
});
```

2024-12-19 08:55 UTC, closed without merging