Option for logging excluded request implemented.
CleanTalk/wordpress-antispam pull request #90
Opened 2021-12-09 12:27 UTC by Glomberg

2021-12-13 07:21 UTC, safronik requested changes

2021-12-13 07:21 UTC, safronik commented on inc/cleantalk-settings.php
> +                ),
Spelling:
**Turn the option on** to log some **type** of **the excluded requests**, like comments from approved authors or POST requests without an Email address
1. Bad sounding. Options: _Enable the option / Turn on the option_
2. If some, then "type" should be plural.

2021-12-13 15:02 UTC, Glomberg commented
All right. 93692c29f682e46cac00acce366edd2e4d67a88c

2021-12-14 07:20 UTC, ArtemAnoshin approved these changes

2021-12-14 08:50 UTC, merged